exports.seed = async function (knex) {
  await knex('albums').withSchema('music_data').del();

  await knex('albums')
    .withSchema('music_data')
    .insert([
      // Álbumes originales
      {
        id: 1,
        title: '1989',
        artist_id: 1,
        release_date: '2014-10-27',
        image_url: 'https://imgur.com/HP6Meux.jpg',
      },
      {
        id: 2,
        title: 'Abbey Road',
        artist_id: 2,
        release_date: '1969-09-26',
        image_url: 'https://imgur.com/bNKaJYD.jpg',
      },
      {
        id: 3,
        title: 'The Marshall Mathers LP',
        artist_id: 3,
        release_date: '2000-05-23',
        image_url: 'https://imgur.com/4uBELpp.jpg',
      },
      {
        id: 4,
        title: 'Kind of Blue',
        artist_id: 4,
        release_date: '1959-08-17',
        image_url: 'https://imgur.com/duTLPZX.jpg',
      },
      {
        id: 5,
        title: 'Symphony No. 5',
        artist_id: 5,
        release_date: '1808-12-22',
        image_url: 'https://imgur.com/drrJdAA.jpg',
      },
      {
        id: 6,
        title: 'Legend',
        artist_id: 6,
        release_date: '1984-05-08',
        image_url: 'https://imgur.com/d8l3Vjc.jpg',
      },
      {
        id: 7,
        title: 'Here You Come Again',
        artist_id: 7,
        release_date: '1977-10-01',
        image_url: 'https://imgur.com/f52oG1g.jpg',
      },
      {
        id: 8,
        title: 'Random Access Memories',
        artist_id: 8,
        release_date: '2013-05-17',
        image_url: 'https://imgur.com/d8dhzNk.jpg',
      },
      {
        id: 9,
        title: 'Lemonade',
        artist_id: 9,
        release_date: '2016-04-23',
        image_url: 'https://imgur.com/OlT4b8S.jpg',
      },
      {
        id: 10,
        title: 'AM',
        artist_id: 10,
        release_date: '2013-09-09',
        image_url: 'https://imgur.com/3B1Tk4R.jpg',
      },

      // Nuevos álbumes
      {
        id: 11,
        title: 'A Night at the Opera',
        artist_id: 11,
        release_date: '1975-11-21',
        image_url: 'https://imgur.com/queenalbum1.jpg',
      },
      {
        id: 12,
        title: 'Thriller',
        artist_id: 12,
        release_date: '1982-11-30',
        image_url: 'https://imgur.com/thriller.jpg',
      },
      {
        id: 13,
        title: 'Led Zeppelin IV',
        artist_id: 13,
        release_date: '1971-11-08',
        image_url: 'https://imgur.com/zeppelin4.jpg',
      },
      {
        id: 14,
        title: 'Views',
        artist_id: 14,
        release_date: '2016-04-29',
        image_url: 'https://imgur.com/views.jpg',
      },
      {
        id: 15,
        title: '21',
        artist_id: 15,
        release_date: '2011-01-24',
        image_url: 'https://imgur.com/adele21.jpg',
      },
      {
        id: 16,
        title: 'To Pimp a Butterfly',
        artist_id: 16,
        release_date: '2015-03-15',
        image_url: 'https://imgur.com/tpab.jpg',
      },
      {
        id: 17,
        title: 'When We All Fall Asleep',
        artist_id: 17,
        release_date: '2019-03-29',
        image_url: 'https://imgur.com/wwafa.jpg',
      },
      {
        id: 18,
        title: 'Master of Puppets',
        artist_id: 18,
        release_date: '1986-03-03',
        image_url: 'https://imgur.com/mop.jpg',
      },
      {
        id: 19,
        title: '÷ (Divide)',
        artist_id: 19,
        release_date: '2017-03-03',
        image_url: 'https://imgur.com/divide.jpg',
      },
      {
        id: 20,
        title: 'After Hours',
        artist_id: 20,
        release_date: '2020-03-20',
        image_url: 'https://imgur.com/afterhours.jpg',
      },
      {
        id: 21,
        title: 'A Love Supreme',
        artist_id: 21,
        release_date: '1965-01-12',
        image_url: 'https://imgur.com/lovesupreme.jpg',
      },
      {
        id: 22,
        title: 'At Folsom Prison',
        artist_id: 22,
        release_date: '1968-05-06',
        image_url: 'https://imgur.com/folsom.jpg',
      },
      {
        id: 23,
        title: 'Currents',
        artist_id: 23,
        release_date: '2015-07-17',
        image_url: 'https://imgur.com/currents.jpg',
      },
      {
        id: 24,
        title: 'YHLQMDLG',
        artist_id: 24,
        release_date: '2020-02-29',
        image_url: 'https://imgur.com/yhlqmdlg.jpg',
      },
      {
        id: 25,
        title: 'Map of the Soul: 7',
        artist_id: 25,
        release_date: '2020-02-21',
        image_url: 'https://imgur.com/mots7.jpg',
      },
      {
        id: 26,
        title: 'Born to Die',
        artist_id: 26,
        release_date: '2012-01-27',
        image_url: 'https://imgur.com/borntodie.jpg',
      },
      {
        id: 27,
        title: 'OK Computer',
        artist_id: 27,
        release_date: '1997-05-21',
        image_url: 'https://imgur.com/okcomputer.jpg',
      },
      {
        id: 28,
        title: 'My Beautiful Dark Twisted Fantasy',
        artist_id: 28,
        release_date: '2010-11-22',
        image_url: 'https://imgur.com/mbdtf.jpg',
      },
      {
        id: 29,
        title: 'The Colour and the Shape',
        artist_id: 29,
        release_date: '1997-05-20',
        image_url: 'https://imgur.com/colourshape.jpg',
      },
      {
        id: 30,
        title: 'Oral Fixation Vol. 2',
        artist_id: 30,
        release_date: '2005-11-28',
        image_url: 'https://imgur.com/oralfixation.jpg',
      },
      {
        id: 31,
        title: 'A Rush of Blood to the Head',
        artist_id: 31,
        release_date: '2002-08-26',
        image_url: 'https://imgur.com/rushofblood.jpg',
      },
      {
        id: 32,
        title: '24K Magic',
        artist_id: 32,
        release_date: '2016-11-18',
        image_url: 'https://imgur.com/24kmagic.jpg',
      },
      {
        id: 33,
        title: 'Anti',
        artist_id: 33,
        release_date: '2016-01-28',
        image_url: 'https://imgur.com/anti.jpg',
      },
      {
        id: 34,
        title: 'Sticky Fingers',
        artist_id: 34,
        release_date: '1971-04-23',
        image_url: 'https://imgur.com/stickyfingers.jpg',
      },
      {
        id: 35,
        title: 'The Fame',
        artist_id: 35,
        release_date: '2008-08-19',
        image_url: 'https://imgur.com/thefame.jpg',
      },
      {
        id: 36,
        title: 'folklore',
        artist_id: 1,
        release_date: '2020-07-24',
        image_url: 'https://imgur.com/folklore.jpg',
      },
      {
        id: 37,
        title: 'Red',
        artist_id: 1,
        release_date: '2012-10-22',
        image_url: 'https://imgur.com/red.jpg',
      },
      {
        id: 38,
        title: 'Revolver',
        artist_id: 2,
        release_date: '1966-08-05',
        image_url: 'https://imgur.com/revolver.jpg',
      },
      {
        id: 39,
        title: 'The Eminem Show',
        artist_id: 3,
        release_date: '2002-05-26',
        image_url: 'https://imgur.com/eminemshow.jpg',
      },
      {
        id: 40,
        title: 'Renaissance',
        artist_id: 9,
        release_date: '2022-07-29',
        image_url: 'https://imgur.com/renaissance.jpg',
      },
    ]);
};
