exports.seed = async function (knex) {
  await knex('songs').withSchema('music_data').del();

  await knex('songs')
    .withSchema('music_data')
    .insert([
      // Canciones originales
      {
        id: 1,
        title: 'Shake It Off',
        duration: '00:03:39',
        album_id: 1,
        artist_id: 1,
        rating: 5,
        genre_id: 1,
        image_url: 'https://example.com/images/shake_it_off.jpg',
      },
      {
        id: 2,
        title: 'Come Together',
        duration: '00:04:19',
        album_id: 2,
        artist_id: 2,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/come_together.jpg',
      },
      {
        id: 3,
        title: 'Stan',
        duration: '00:04:56',
        album_id: 3,
        artist_id: 3,
        rating: 5,
        genre_id: 3,
        image_url: 'https://example.com/images/stan.jpg',
      },
      {
        id: 4,
        title: 'So What',
        duration: '00:03:35',
        album_id: 3,
        artist_id: 3,
        rating: 4,
        genre_id: 3,
        image_url: 'https://example.com/images/so_what.jpg',
      },
      {
        id: 5,
        title: 'Freddie Freeloader',
        duration: '00:09:53',
        album_id: 4,
        artist_id: 4,
        rating: 5,
        genre_id: 4,
        image_url: 'https://example.com/images/freddie_freeloader.jpg',
      },
      {
        id: 6,
        title: 'Für Elise',
        duration: '00:02:55',
        album_id: 5,
        artist_id: 5,
        rating: 5,
        genre_id: 5,
        image_url: 'https://example.com/images/fur_elise.jpg',
      },
      {
        id: 7,
        title: 'No Woman, No Cry',
        duration: '00:07:06',
        album_id: 6,
        artist_id: 6,
        rating: 5,
        genre_id: 6,
        image_url: 'https://example.com/images/no_woman_no_cry.jpg',
      },
      {
        id: 8,
        title: 'Jolene',
        duration: '00:02:41',
        album_id: 7,
        artist_id: 7,
        rating: 4,
        genre_id: 7,
        image_url: 'https://example.com/images/jolene.jpg',
      },
      {
        id: 9,
        title: 'Get Lucky',
        duration: '00:06:09',
        album_id: 8,
        artist_id: 8,
        rating: 5,
        genre_id: 8,
        image_url: 'https://example.com/images/get_lucky.jpg',
      },
      {
        id: 10,
        title: 'Formation',
        duration: '00:03:26',
        album_id: 9,
        artist_id: 9,
        rating: 5,
        genre_id: 9,
        image_url: 'https://example.com/images/formation.jpg',
      },
      {
        id: 11,
        title: 'Do I Wanna Know?',
        duration: '00:04:01',
        album_id: 10,
        artist_id: 10,
        rating: 5,
        genre_id: 10,
        image_url: 'https://example.com/images/do_i_wanna_know.jpg',
      },

      // Nuevas canciones - Queen
      {
        id: 12,
        title: 'Bohemian Rhapsody',
        duration: '00:05:55',
        album_id: 11,
        artist_id: 11,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/bohemian.jpg',
      },
      {
        id: 13,
        title: 'We Will Rock You',
        duration: '00:02:01',
        album_id: 11,
        artist_id: 11,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/rockyou.jpg',
      },

      // Michael Jackson
      {
        id: 14,
        title: 'Billie Jean',
        duration: '00:04:54',
        album_id: 12,
        artist_id: 12,
        rating: 5,
        genre_id: 1,
        image_url: 'https://example.com/images/billiejean.jpg',
      },
      {
        id: 15,
        title: 'Beat It',
        duration: '00:04:18',
        album_id: 12,
        artist_id: 12,
        rating: 5,
        genre_id: 1,
        image_url: 'https://example.com/images/beatit.jpg',
      },

      // Led Zeppelin
      {
        id: 16,
        title: 'Stairway to Heaven',
        duration: '00:08:02',
        album_id: 13,
        artist_id: 13,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/stairway.jpg',
      },
      {
        id: 17,
        title: 'Black Dog',
        duration: '00:04:54',
        album_id: 13,
        artist_id: 13,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/blackdog.jpg',
      },

      // Drake
      {
        id: 18,
        title: 'Hotline Bling',
        duration: '00:04:27',
        album_id: 14,
        artist_id: 14,
        rating: 4,
        genre_id: 3,
        image_url: 'https://example.com/images/hotline.jpg',
      },
      {
        id: 19,
        title: 'One Dance',
        duration: '00:02:53',
        album_id: 14,
        artist_id: 14,
        rating: 4,
        genre_id: 3,
        image_url: 'https://example.com/images/onedance.jpg',
      },

      // Adele
      {
        id: 20,
        title: 'Rolling in the Deep',
        duration: '00:03:48',
        album_id: 15,
        artist_id: 15,
        rating: 5,
        genre_id: 1,
        image_url: 'https://example.com/images/rolling.jpg',
      },
      {
        id: 21,
        title: 'Someone Like You',
        duration: '00:04:45',
        album_id: 15,
        artist_id: 15,
        rating: 5,
        genre_id: 1,
        image_url: 'https://example.com/images/someone.jpg',
      },

      // Kendrick Lamar
      {
        id: 22,
        title: 'Alright',
        duration: '00:03:39',
        album_id: 16,
        artist_id: 16,
        rating: 5,
        genre_id: 3,
        image_url: 'https://example.com/images/alright.jpg',
      },
      {
        id: 23,
        title: 'King Kunta',
        duration: '00:03:54',
        album_id: 16,
        artist_id: 16,
        rating: 5,
        genre_id: 3,
        image_url: 'https://example.com/images/kingkunta.jpg',
      },

      // Billie Eilish
      {
        id: 24,
        title: 'bad guy',
        duration: '00:03:14',
        album_id: 17,
        artist_id: 17,
        rating: 5,
        genre_id: 10,
        image_url: 'https://example.com/images/badguy.jpg',
      },
      {
        id: 25,
        title: "when the party's over",
        duration: '00:03:16',
        album_id: 17,
        artist_id: 17,
        rating: 5,
        genre_id: 10,
        image_url: 'https://example.com/images/partyover.jpg',
      },

      // Metallica
      {
        id: 26,
        title: 'Master of Puppets',
        duration: '00:08:35',
        album_id: 18,
        artist_id: 18,
        rating: 5,
        genre_id: 11,
        image_url: 'https://example.com/images/masterpuppets.jpg',
      },
      {
        id: 27,
        title: 'Battery',
        duration: '00:05:12',
        album_id: 18,
        artist_id: 18,
        rating: 5,
        genre_id: 11,
        image_url: 'https://example.com/images/battery.jpg',
      },

      // Ed Sheeran
      {
        id: 28,
        title: 'Shape of You',
        duration: '00:03:53',
        album_id: 19,
        artist_id: 19,
        rating: 4,
        genre_id: 1,
        image_url: 'https://example.com/images/shapeofyou.jpg',
      },
      {
        id: 29,
        title: 'Perfect',
        duration: '00:04:23',
        album_id: 19,
        artist_id: 19,
        rating: 5,
        genre_id: 1,
        image_url: 'https://example.com/images/perfect.jpg',
      },

      // The Weeknd
      {
        id: 30,
        title: 'Blinding Lights',
        duration: '00:03:20',
        album_id: 20,
        artist_id: 20,
        rating: 5,
        genre_id: 9,
        image_url: 'https://example.com/images/blinding.jpg',
      },
      {
        id: 31,
        title: 'Save Your Tears',
        duration: '00:03:35',
        album_id: 20,
        artist_id: 20,
        rating: 5,
        genre_id: 9,
        image_url: 'https://example.com/images/savetears.jpg',
      },

      // John Coltrane
      {
        id: 32,
        title: 'A Love Supreme, Part 1',
        duration: '00:07:47',
        album_id: 21,
        artist_id: 21,
        rating: 5,
        genre_id: 4,
        image_url: 'https://example.com/images/lovesupreme1.jpg',
      },

      // Johnny Cash
      {
        id: 33,
        title: 'Folsom Prison Blues',
        duration: '00:02:42',
        album_id: 22,
        artist_id: 22,
        rating: 5,
        genre_id: 7,
        image_url: 'https://example.com/images/folsomblues.jpg',
      },

      // Tame Impala
      {
        id: 34,
        title: 'The Less I Know The Better',
        duration: '00:03:36',
        album_id: 23,
        artist_id: 23,
        rating: 5,
        genre_id: 10,
        image_url: 'https://example.com/images/lessiknow.jpg',
      },

      // Bad Bunny
      {
        id: 35,
        title: 'Safaera',
        duration: '00:04:55',
        album_id: 24,
        artist_id: 24,
        rating: 5,
        genre_id: 14,
        image_url: 'https://example.com/images/safaera.jpg',
      },

      // BTS
      {
        id: 36,
        title: 'Dynamite',
        duration: '00:03:19',
        album_id: 25,
        artist_id: 25,
        rating: 5,
        genre_id: 15,
        image_url: 'https://example.com/images/dynamite.jpg',
      },

      // Lana Del Rey
      {
        id: 37,
        title: 'Video Games',
        duration: '00:04:42',
        album_id: 26,
        artist_id: 26,
        rating: 5,
        genre_id: 1,
        image_url: 'https://example.com/images/videogames.jpg',
      },

      // Radiohead
      {
        id: 38,
        title: 'Paranoid Android',
        duration: '00:06:23',
        album_id: 27,
        artist_id: 27,
        rating: 5,
        genre_id: 10,
        image_url: 'https://example.com/images/paranoid.jpg',
      },

      // Kanye West
      {
        id: 39,
        title: 'Power',
        duration: '00:04:52',
        album_id: 28,
        artist_id: 28,
        rating: 5,
        genre_id: 3,
        image_url: 'https://example.com/images/power.jpg',
      },

      // Foo Fighters
      {
        id: 40,
        title: 'Everlong',
        duration: '00:04:10',
        album_id: 29,
        artist_id: 29,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/everlong.jpg',
      },

      // Shakira
      {
        id: 41,
        title: "Hips Don't Lie",
        duration: '00:03:38',
        album_id: 30,
        artist_id: 30,
        rating: 5,
        genre_id: 14,
        image_url: 'https://example.com/images/hipsdontlie.jpg',
      },

      // Coldplay
      {
        id: 42,
        title: 'Clocks',
        duration: '00:05:07',
        album_id: 31,
        artist_id: 31,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/clocks.jpg',
      },

      // Bruno Mars
      {
        id: 43,
        title: '24K Magic',
        duration: '00:03:45',
        album_id: 32,
        artist_id: 32,
        rating: 5,
        genre_id: 9,
        image_url: 'https://example.com/images/24kmagic.jpg',
      },

      // Rihanna
      {
        id: 44,
        title: 'Work',
        duration: '00:03:39',
        album_id: 33,
        artist_id: 33,
        rating: 4,
        genre_id: 1,
        image_url: 'https://example.com/images/work.jpg',
      },

      // Rolling Stones
      {
        id: 45,
        title: 'Brown Sugar',
        duration: '00:03:48',
        album_id: 34,
        artist_id: 34,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/brownsugar.jpg',
      },

      // Lady Gaga
      {
        id: 46,
        title: 'Poker Face',
        duration: '00:03:57',
        album_id: 35,
        artist_id: 35,
        rating: 5,
        genre_id: 1,
        image_url: 'https://example.com/images/pokerface.jpg',
      },

      // Taylor Swift - álbumes adicionales
      {
        id: 47,
        title: 'cardigan',
        duration: '00:03:59',
        album_id: 36,
        artist_id: 1,
        rating: 5,
        genre_id: 1,
        image_url: 'https://example.com/images/cardigan.jpg',
      },
      {
        id: 48,
        title: 'All Too Well',
        duration: '00:05:29',
        album_id: 37,
        artist_id: 1,
        rating: 5,
        genre_id: 1,
        image_url: 'https://example.com/images/alltoowell.jpg',
      },

      // The Beatles - álbum adicional
      {
        id: 49,
        title: 'Eleanor Rigby',
        duration: '00:02:06',
        album_id: 38,
        artist_id: 2,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/eleanor.jpg',
      },

      // Eminem - álbum adicional
      {
        id: 50,
        title: 'Lose Yourself',
        duration: '00:05:26',
        album_id: 39,
        artist_id: 3,
        rating: 5,
        genre_id: 3,
        image_url: 'https://example.com/images/loseyourself.jpg',
      },

      // Beyoncé - álbum adicional
      {
        id: 51,
        title: 'Break My Soul',
        duration: '00:04:38',
        album_id: 40,
        artist_id: 9,
        rating: 5,
        genre_id: 9,
        image_url: 'https://example.com/images/breakmysoul.jpg',
      },

      // Más canciones variadas
      {
        id: 52,
        title: "Sweet Child O' Mine",
        duration: '00:05:03',
        album_id: 13,
        artist_id: 13,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/sweetchild.jpg',
      },
      {
        id: 53,
        title: 'Smells Like Teen Spirit',
        duration: '00:05:01',
        album_id: 29,
        artist_id: 29,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/teenspirit.jpg',
      },
      {
        id: 54,
        title: 'Hotel California',
        duration: '00:06:30',
        album_id: 34,
        artist_id: 34,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/hotelcalifornia.jpg',
      },
      {
        id: 55,
        title: 'Imagine',
        duration: '00:03:03',
        album_id: 2,
        artist_id: 2,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/imagine.jpg',
      },
      {
        id: 56,
        title: 'Like a Rolling Stone',
        duration: '00:06:13',
        album_id: 34,
        artist_id: 34,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/rollingstone.jpg',
      },
      {
        id: 57,
        title: 'Hey Jude',
        duration: '00:07:11',
        album_id: 2,
        artist_id: 2,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/heyjude.jpg',
      },
      {
        id: 58,
        title: 'Yesterday',
        duration: '00:02:05',
        album_id: 38,
        artist_id: 2,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/yesterday.jpg',
      },
      {
        id: 59,
        title: 'Let It Be',
        duration: '00:04:03',
        album_id: 2,
        artist_id: 2,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/letitbe.jpg',
      },
      {
        id: 60,
        title: 'Wonderwall',
        duration: '00:04:18',
        album_id: 31,
        artist_id: 31,
        rating: 5,
        genre_id: 2,
        image_url: 'https://example.com/images/wonderwall.jpg',
      },
      {
        id: 61,
        title: 'Boogie Wonderland',
        duration: '00:04:48',
        album_id: 8,
        artist_id: 8,
        rating: 4,
        genre_id: 8,
        image_url: 'https://example.com/images/boogie.jpg',
      },
      {
        id: 62,
        title: 'Around the World',
        duration: '00:07:09',
        album_id: 8,
        artist_id: 8,
        rating: 4,
        genre_id: 8,
        image_url: 'https://example.com/images/aroundworld.jpg',
      },
      {
        id: 63,
        title: 'One More Time',
        duration: '00:05:20',
        album_id: 8,
        artist_id: 8,
        rating: 5,
        genre_id: 8,
        image_url: 'https://example.com/images/onemoretime.jpg',
      },
      {
        id: 64,
        title: 'Digital Love',
        duration: '00:05:01',
        album_id: 8,
        artist_id: 8,
        rating: 5,
        genre_id: 8,
        image_url: 'https://example.com/images/digitallove.jpg',
      },
      {
        id: 65,
        title: 'Harder, Better, Faster, Stronger',
        duration: '00:03:45',
        album_id: 8,
        artist_id: 8,
        rating: 5,
        genre_id: 8,
        image_url: 'https://example.com/images/harderbetter.jpg',
      },
      {
        id: 66,
        title: 'Technologic',
        duration: '00:04:44',
        album_id: 8,
        artist_id: 8,
        rating: 4,
        genre_id: 8,
        image_url: 'https://example.com/images/technologic.jpg',
      },
      {
        id: 67,
        title: 'Robot Rock',
        duration: '00:04:47',
        album_id: 8,
        artist_id: 8,
        rating: 4,
        genre_id: 8,
        image_url: 'https://example.com/images/robotrock.jpg',
      },
      {
        id: 68,
        title: 'Television Rules the Nation',
        duration: '00:04:47',
        album_id: 8,
        artist_id: 8,
        rating: 3,
        genre_id: 8,
        image_url: 'https://example.com/images/television.jpg',
      },
      {
        id: 69,
        title: 'Human After All',
        duration: '00:05:19',
        album_id: 8,
        artist_id: 8,
        rating: 4,
        genre_id: 8,
        image_url: 'https://example.com/images/humanafterall.jpg',
      },
      {
        id: 70,
        title: 'Make Love',
        duration: '00:04:50',
        album_id: 8,
        artist_id: 8,
        rating: 3,
        genre_id: 8,
        image_url: 'https://example.com/images/makelove.jpg',
      },
      {
        id: 71,
        title: 'The Brainwasher',
        duration: '00:04:08',
        album_id: 8,
        artist_id: 8,
        rating: 3,
        genre_id: 8,
        image_url: 'https://example.com/images/brainwasher.jpg',
      },
      {
        id: 72,
        title: 'On/Off',
        duration: '00:00:19',
        album_id: 8,
        artist_id: 8,
        rating: 2,
        genre_id: 8,
        image_url: 'https://example.com/images/onoff.jpg',
      },
      {
        id: 73,
        title: 'Touch',
        duration: '00:08:18',
        album_id: 8,
        artist_id: 8,
        rating: 5,
        genre_id: 8,
        image_url: 'https://example.com/images/touch.jpg',
      },
      {
        id: 74,
        title: 'Within',
        duration: '00:03:48',
        album_id: 8,
        artist_id: 8,
        rating: 4,
        genre_id: 8,
        image_url: 'https://example.com/images/within.jpg',
      },
      {
        id: 75,
        title: 'Beyond',
        duration: '00:04:50',
        album_id: 8,
        artist_id: 8,
        rating: 4,
        genre_id: 8,
        image_url: 'https://example.com/images/beyond.jpg',
      },
      {
        id: 76,
        title: 'Motherboard',
        duration: '00:05:41',
        album_id: 8,
        artist_id: 8,
        rating: 4,
        genre_id: 8,
        image_url: 'https://example.com/images/motherboard.jpg',
      },
      {
        id: 77,
        title: 'Fragments of Time',
        duration: '00:04:39',
        album_id: 8,
        artist_id: 8,
        rating: 4,
        genre_id: 8,
        image_url: 'https://example.com/images/fragments.jpg',
      },
      {
        id: 78,
        title: "Doin' It Right",
        duration: '00:04:11',
        album_id: 8,
        artist_id: 8,
        rating: 5,
        genre_id: 8,
        image_url: 'https://example.com/images/doinitright.jpg',
      },
      {
        id: 79,
        title: 'Contact',
        duration: '00:06:21',
        album_id: 8,
        artist_id: 8,
        rating: 4,
        genre_id: 8,
        image_url: 'https://example.com/images/contact.jpg',
      },
      {
        id: 80,
        title: 'Horizon',
        duration: '00:04:24',
        album_id: 8,
        artist_id: 8,
        rating: 3,
        genre_id: 8,
        image_url: 'https://example.com/images/horizon.jpg',
      },
    ]);
};
